### ISSUE TITLE
Retorno de XML MAL FORMADO

### ISSUE THREAD

**Issue by brugaspar** [marcosjara/facturacionelectronicapy-xmlgen#14]
Ya había realizado varias pruebas de generación de facturas electrónicas y todas se habían realizado con éxito, pero en mis últimas pruebas me ha aparecido el mensaje "XML MAL FORMADO". Estoy enviando el mismo XML que envié en las otras pruebas. Qué puede ser, cómo proceder?

![error](https://github.com/TIPS-SA/facturacionelectronicapy-xmlgen/assets/54087072/c92e94df-87b2-4698-9508-57925365452b)

**Comment by nicoaguilerapy** [comment]
Me suele ocurrir cuando el servidor de la SET no funciona
